### ISSUE TITLE
v1.0 Release Checklist

### ISSUE THREAD

**Issue by getify** [getify/Typl#24]
- [ ] Narrower number type inference #17
- [ ] Persistent object/array type signatures #18
- [ ] Compiler: basic transforms #19
- [ ] Specific type exceptions #20
- [ ] Basic configuration #21
- [ ] Fix architecture of `check(..)` method #22
- [ ] Basic checker tests #23

**Comment by dgutson** [comment]
@getify any update on this?

**Comment by getify** [comment]
Unfortunately, no. I didn't really get the uptake in interest I was hoping and trying to evangelize for, so this project has just been indefinitely on the shelf. It's far too ambitious for me to have done myself.

My thoughts around type annotation have moved over to the design of [a new programming language](https://github.com/getify/foi-lang), which is where my active efforts are currently focused.

This project is not necessarily permanently shuttered, but I don't see it coming out of hibernation unless I found some financial backing and a group of interested contributors to help me.

**Comment by dgutson** [comment]
Would you do the last effort and finish the last 5 tasks to do the release honoring all your previous effort? I personally find this project more useful and applicable than a brand new language for the every-day working layman.

Finding contributors would be easier for a baselined 1.0.
Also, maybe you could do a university tech talk about this project (I can contact you later).

**Comment by getify** [comment]
> Would you do the last effort and finish the last 5 tasks

At the time I was actively working on this, I felt like I was about 60% of the way to a 1.0 release, and that I probably had about 4 months FT effort to complete it. I would *love* to have 4 months to dedicate to this, but I cannot afford that. And working on it a few hours at a time would take a year or two, which I just don't have the long-term interest in enough to sustain.

If I found funding to pay for 4 months of my effort, I would probably do it. But I spent a fair bit of effort shopping this around to some companies and folks I knew, and most of them felt it was not a worthy investment because TypeScript was so inevitable as the "winner" in this space.

**Comment by dgutson** [comment]
Are you familiar with Instagram's MonkeyType? Could TypL be the basis for an equivalent for javascript?

**Comment by getify** [comment]
Never heard of it, but I just took a quick glance at the README.

One of the modes/tools I had planned for TypL was in fact to be able to gather runtime types (from test suite and/or even staging/production code) and export that information as TypL annotations (diffs that could be applied back to code).

That would definitely have been post-1.0, but yes, I think it's a great idea and I definitely had hoped to build something like that. :)
